version: "3"  

services:  
  mongo-express:  
    image: mongo-express  
    ports:  
      - 8081:8081  
    environment:  
      ME_CONFIG_BASICAUTH_USERNAME: mvs  
      ME_CONFIG_BASICAUTH_PASSWORD: mvs@123  
      ME_CONFIG_MONGODB_PORT: 27017  
    links:  
      - mongo  
    networks:  
      - mongo-compose-network

  mongo:  
    image: mongo  
    ports:  
      - "27017:27017"  
    volumes:  
      - /home/regis/data/volumes/MongoDB:/data/db  
    networks:  
      - mongo-compose-network  
  
  redis:  
    image: redis  
    command: redis-server  
    ports:  
      - "6379:6379"

networks:
  mongo-compose-network:  
    driver: bridge  