CREATE DATABASE JVSAONLINE_PRD;
GO
USE JVSAONLINE_PRD;
GO
CREATE TABLE CADASTRO_FIDELIDADE
(
    CPF DECIMAL(20,0) PRIMARY KEY,
    FILIAL INT,
    DATA_INCLUSAO SMALLDATETIME,
    DATA_ALTERACAO SMALLDATETIME,
    NOME NVARCHAR(200),
    DDDCEL INT,
    CEL NVARCHAR(20),
    EMAIL NVARCHAR(200),
    CEP NVARCHAR(20),
    ENDERECO NVARCHAR(200),
    NUMERO NVARCHAR(50),
    COMP NVARCHAR(200),
    BAIRRO NVARCHAR(200),
    CIDADE NVARCHAR(200),
    ESTADO NVARCHAR(200),
    DATANASC SMALLDATETIME,
    DATA_VERIF BIT,
    SEXO NVARCHAR(20),
    OPT_SMS BIT,
    OPT_EMAIL BIT,
    ORIGEM NVARCHAR(200),
    CODIGO_EMPRESA INT,
    USO_CONTINUO_MED BIT,
    DESATIVADO BIT,
    CLASSIFICACAO INT,
    APOIO_TRATAMENTO BIT,
    CLIENTE_TOP BIT,
    VIP_CAT NVARCHAR(200),
    mostra_vip BIT,
    BIOMETRIA BIT,
    BIOMETRIA_DATA SMALLDATETIME,
    ASSINATURA BIT,
    ASSINATURA_DATA SMALLDATETIME
);
GO
CREATE TABLE ACCEPTANCE_TERMS
(
    ID INT PRIMARY KEY,
    CPF VARCHAR(11),
    NOTE_ID VARCHAR(50),
    NOTE_NAME VARCHAR(50),
    NOTE_TYPE VARCHAR(50),
    AGREED BIT,
    ACCEPTED_DATE SMALLDATETIME,
    UPDATED_DATE SMALLDATETIME,
    CHANNEL VARCHAR(20),
    ORIGIN VARCHAR(100)
);
