version: '3.4'

services:
  mvs-db-sql: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes: 
      - db-data:/var/lib/mssql/data
    ports:
      - "49841:1433"
    environment: 
      MSSQL_SA_PASSWORD: DB_APP_USER
      ACCEPT_EULA: "Y"     
    restart: unless-stopped
    tty: true
    
  
volumes: 
  db-data:
    driver: local